# Site settings
title: Conduct of Code
email: henrik@laueriksson.com
description: "Henrik Lau Eriksson on the conduct of code"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conductofcode.io" # the base hostname & protocol for your site
twitter_username: hlaueriksson
github_username:  hlaueriksson

portfolio_url: "http://henrik.laueriksson.com"
portfolio_text: "henrik.laueriksson.com"

# Build settings
markdown: kramdown
timezone: Europe/Stockholm
permalink: /post/:title/
