# Site settings
title: Conduct of Code
email: henrik@laueriksson.com
description: "Henrik Lau Eriksson on the conduct of code"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://conductofcode.io" # the base hostname & protocol for your site
twitter_username: hlaueriksson
github_username:  hlaueriksson

author: "Henrik Lau Eriksson"

portfolio_url: "https://henrik.laueriksson.com"
portfolio_text: "henrik.laueriksson.com"

gravatar_url: "https://s.gravatar.com/avatar/27df7a0a062537ef9116a1572707d5e0?s=60"

# Google Analytics
google_analytics_tracking_id: UA-39767110-6

# Build settings
markdown: kramdown
timezone: Europe/Stockholm
permalink: /post/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      is_post: true

gems:
  - jekyll-sitemap
  - jekyll-gist

gist:
  noscript: true
