title: Conduct of Code
author: Henrik Lau Eriksson
email: henrik@laueriksson.com
description: Henrik Lau Eriksson on the conduct of code

url: "https://conductofcode.io"

lang: en-us

google_analytics: UA-39767110-6

# social links
github_username:  hlaueriksson
twitter_username: hlaueriksson
#linkedin_username: henriklaueriksson
rss: RSS

# seo
twitter:
  username: hlaueriksson
  card: summary

# custom
portfolio:
  url: https://henrik.laueriksson.com
  text: henrik.laueriksson.com

# build settings
theme: minima
timezone: Europe/Stockholm
permalink: /post/:title/

minima:
  date_format: "%d %B %Y"

exclude: [Gemfile, Gemfile.lock, README.md, docker-compose.yml]

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap